- title: NACTA OSINT Training
  subtitle: Led a one-week OSINT training program for newly inducted analysts at the IB Academy in Islamabad, Pakistan, on behalf of NACTA
  link: https://nacta.gov.pk/
  year: 2023
- title: Trainer, Digital Pakistan Cybersecurity Hackathon - 2023
  subtitle: Contributed as a trainer in Ignite's Cybersecurity Hackathon, providing hands-on training to participants. The event aimed to foster cyber resilience in Pakistan by addressing the shortage of cybersecurity professionals and promoting innovation and preparedness
  link: https://cyberhackathon.pk/
  year: 2023
