- title: "NACTA OSINT Training - Phase 1"
  subtitle: "Led a one-week OSINT training program for newly inducted analysts at the IB Academy in Islamabad, Pakistan, on behalf of NACTA"
  link: "https://nacta.gov.pk/"
  year: 2023

- title: "Trainer, Digital Pakistan Cybersecurity Hackathon - 2023"
  subtitle: "Contributed as a trainer in Ignite's Cybersecurity Hackathon, providing hands-on training to participants. The event aimed to foster cyber resilience in Pakistan by addressing the shortage of cybersecurity professionals and promoting innovation and preparedness."
  link: "https://cyberhackathon.pk/"
  year: 2023

- title: "OSINT Hands-On Training Workshop for NACTA - Phase 2"
  subtitle: "I am currently part of the team conducting the 'OSINT Hands-On Training Workshop for NACTA.' My focus is on Social Media Search & Analytics. We explore Social Media Intelligence Collection, including hands-on exercises on platforms like Twitter, Facebook, LinkedIn, Instagram, Youtube, Snapchat, TikTok, and more. It's an engaging session aimed at enhancing OSINT skills in Social Media Intelligence."
  link: "https://nacta.gov.pk/"
  year: 2023
